* wip

diff --git a/src/bash_completion/cm b/src/bash_completion/cm
--- a/src/bash_completion/cm
+++ b/src/bash_completion/cm
@@ -1,8 +1,10 @@
 #. cmlib
+. ${__cm_lib_dir}/cmlib
 
 # $1 = dir to list
-__cm_complete_indir()
+__cm_complete_node()
 {
+	local root alldir base
 	cur="${COMP_WORDS[COMP_CWORD]}"
 	if [ -z "$1" ]; then
 		root="$__cm_libexec_dir"
@@ -16,18 +18,18 @@ __cm_complete_indir()
 	for dir in "$root"/*; do	
 		base=$(basename "$dir")
 		[ "${base:0:1}" != "_" ] && alldir="$alldir $base"
-		[ "$base" == "_tag" ] && alldir="$alldir $($root/_tag/_tag_complete)"
 	done
 	COMPREPLY=($(compgen -W "$alldir" -- "$cur" ))
 	return 
 }
 
-__cm_complete_command()
+__cm_complete_leaf()
 {
+	local dirname filename command cur complete
 	dirname=$(dirname $1)
 	filename=$(basename $1)
 	command="${dirname}/_${filename}_complete"
-	local IFS=$'\n'
+	#local IFS=$'\n'
 	COMPREPLY=()
 	cur="${COMP_WORDS[COMP_CWORD]}"
 	if [ -f "${dirname}/_${filename}_nocomplete" ]; then
@@ -44,39 +46,32 @@ __cm_complete_command()
 
 __cm_complete()
 {
-	local cur prev __cm_root_all
-	cur="${COMP_WORDS[COMP_CWORD]}"
-	prev="${COMP_WORDS[COMP_CWORD-1]}"
+	local cur prev __cm_root_all path command
+	cur=${COMP_WORDS[COMP_CWORD]}
+	prev=${COMP_WORDS[COMP_CWORD-1]}
 
 	opts=${COMP_WORDS[@]:1}
-	opts_path=${__cm_libexec_dir}/${opts// /\/}
-	
 	prev_opts=${COMP_WORDS[@]:1:$((${#COMP_WORDS[@]} - 2))}
-	prev_opts_path=${__cm_libexec_dir}/${prev_opts// /\/}
-	# root of tree
-	# echo $opts_path
+	#COMPREPLY=()
 	if [ "$prev" == "cm" ]; then
-		command=""
-		__cm_complete_indir
-		return
-	elif [  -d "$prev_opts_path" ]; then
-		__cm_complete_indir "$prev_opts_path"
-		return
-	# directory in libexec
-	elif [ -d "$opts_path" ]; then
-		__cm_complete_indir "$opts_path"
-		return
-	# file in libexec
-	elif [  -f "$opts_path" ]; then
-		__cm_complete_command "$prev_opts_path"
-		return
-	# file complete
-	elif [  -f "$prev_opts_path" ]; then
-		__cm_complete_command "$prev_opts_path"
+		COMPREPLY=($(compgen -W "$(__cm_list_node)" -- "$cur" ))
 		return
 	fi
-	#echo "NOT FOUND"
-	return 0
+	
+	__cm_is_command_node $opts
+	if [ "$?" == "0" ]; then
+		COMPREPLY=($(compgen -W "$(__cm_list_node $opts)" -- "$cur" ))
+		return
+	fi
+	# prev is a node
+	__cm_is_command_node $prev_opts
+	if [ "$?" == "0" ]; then
+		COMPREPLY=($(compgen -W "$(__cm_list_node $prev_opts)" -- "$cur" ))
+		return
+	fi
+
+	echo "NOT FOUND"
+	#return 0
 }
 
 complete -F __cm_complete cm
